
-- user: joseMarciano
CREATE TABLE CATEGORIES (
    ID VARCHAR(16) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    FL_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    DELETED_AT DATETIME(6)
);
-- rollback DROP TABLE CATEGORY