
-- user: joseMarciano
CREATE TABLE GENRES (
    ID CHAR(32) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    FL_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    DELETED_AT DATETIME(6)
);
-- rollback DROP TABLE GENRES


CREATE TABLE GENRES_CATEGORIES (
    ID_GENRES CHAR(32) NOT NULL,
    ID_CATEGORIES CHAR(32) NOT NULL,
    CONSTRAINT IDX_GENRES_CATEGORIES UNIQUE (ID_GENRES, ID_CATEGORIES),
    CONSTRAINT FK_ID_GENRES FOREIGN KEY (ID_GENRES) REFERENCES GENRES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ID_CATEGORIES FOREIGN KEY (ID_CATEGORIES) REFERENCES CATEGORIES(ID) ON DELETE CASCADE
);
-- rollback DROP TABLE GENRES_CATEGORIES
