keycloak:
  host: http://localhost:8443
  realm: fc3-codeflix

mysql:
  url: ${DATABASE_MYSQL_URL}
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: adm_videos

amqp:
  admin:
    auto-create: true
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}


server:
  undertow:
    threads:
      worker: 10
      io: 2
