mysql:
  url: localhost:3306
  username: root
  password: 123456
  schema: adm_videos

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: admin_videos
  password: 123456


server:
  undertow:
    threads:
      worker: 10
      io: 2
